### PR TITLE
fixes #30: auto generate type definitions from source

### LINKED ISSUE #30: Wrong TypeScript type definitions
Hi. I've just updated the package to the latest version and got this TS error:`Value of type 'typeof Lru' is not callable. Did you mean to include 'new'`

TS is tricked to think that the class is exported instead of the factory function. 
In https://github.com/avoidwork/tiny-lru/blob/master/src/lru.js#L137 we can see that the factory is exported, instead of the constructor as written here https://github.com/avoidwork/tiny-lru/blob/master/tiny-lru.d.ts#L2

Let me know if you need help with this.

### PR DESCRIPTION
**Pull request by osdevisnot**
Auto Generate Type Definitions from Source.

Details in comments.

### CODE REVIEW

File: lib/lru.d.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+    has(key: string): boolean;
+    clear(): this;
+    delete(key: string): this;
+    evict(): this;
+    get(key: string): T;
+    keys(): string[];
+    set(key: string, value: T, bypass?: boolean): this;
+}
+export default function factory(max?: number, ttl?: number): LRU<any>;
+export {};
```
Comment (osdevisnot) [inline lib/lru.d.ts]: The auto generated Type Definitions.

File: lib/tiny-lru.esm.js [hunk 2]
```diff
@@ -1,149 +1,118 @@
...
+    if (isNaN(max) || max < 0) {
+        throw new TypeError("Invalid max value");
+    }
+    if (isNaN(ttl) || ttl < 0) {
+        throw new TypeError("Invalid ttl value");
+    }
+    return new LRU(max, ttl);
+}
 
 export default factory;
```
Comment (osdevisnot) [inline lib/tiny-lru.esm.js]: Same as above, compiled output creating noise in PR

File: package.json [hunk 3]
```diff
@@ -16,11 +16,11 @@
     "*.d.ts"
   ],
   "license": "BSD-3-Clause",
-  "source": "src/lru.js",
+  "source": "src/lru.ts",
```
Comment (osdevisnot) [inline package.json]: we rename `js` to `ts` to be able to generate the type definitions.

Note: Currently its mandatory to port code to TS as `allowJS` and `declaration` options in TS won't work together. This will be address very soon - https://dev.to/open-wc/generating-typescript-definition-files-from-javascript-5bp2, at which point, we can convert this back to `js` if needed.

File: src/lru.ts [hunk 4]
```diff
@@ -1,4 +1,12 @@
-	class LRU {
+	class LRU<T = any> {
```
Comment (osdevisnot) [inline src/lru.ts]: This file is a gist of this PR. We adhere to TS rules and provide hint where TS might need help.

Note: For this pr, I am attempting to do minimal type definitions. This can be improvised to have even internal variables typed.

File: lib/lru.d.ts (hunk 1 above)
Comment (fox1t) [reply lib/lru.d.ts]: There is a problem with a missing generics in factory. We need to expose `factory<T = any>(...)` to allow types being handled and propagated to the rest of the user code.

**Comment by fox1t** [comment]
I don't fully understand this PR: is this a port to TS?

File: lib/lru.d.ts (hunk 1 above)
Comment (osdevisnot) [reply lib/lru.d.ts]: yeah let me look into this more. TS compiler seems to think otherwise.

**Comment by osdevisnot** [comment]
> I don't fully understand this PR: is this a port to TS?

umm, technically yes.

File: lib/lru.d.ts (hunk 1 above)
Comment (fox1t) [reply lib/lru.d.ts]: What do you mean with "TS compiler seems to think otherwise"?

**Comment by avoidwork** [comment]
hi, i totally missed this in my day to day work; imma merge and deploy assuming it's all good.

**Comment by avoidwork** [comment]
I rushed that merge, so this is reverted cause it's not a typescript project. solve your issues another way.

File: src/lru.ts (hunk 4 above)
Comment (avoidwork) [reply src/lru.ts]: this is the fundamental problem with typescript... `any` is what the following `key`s need to be because number or string is valid, but then people will complain... because there's no value at that point from the typescript pov. code completion already works with an IDE, so ... I don't see the point of these actions taken... it doesn't impact how it runs.

**Comment by fox1t** [comment]
As I pointed out on the issue, there is no need to rewrite the whole project in TypeScript to fix this problem. It is one line fix in the types file.

**Comment by osdevisnot** [comment]
This is going to be so much easier when typescript 3.7 lands. I can't wait to see `.tsd` being generated from jsdoc comments.

**Comment by avoidwork** [comment]
that's one of the plans? man. bums me out. jsdoc was in this project for 1.0.0 and everything else i was producing 5-10yr ago. i eventually removed it cause no one seemed to care about it or what i could gen with it. sigh.

https://github.com/avoidwork/tiny-lru/commit/0c64c8acb7b18bd565e3ac9d5b952620ecae4df0

**Comment by avoidwork** [comment]
^ there was a period when everyone was byte crazy... gotta cut as much as possible! lol/sigh

**Comment by fox1t** [comment]
> This is going to be so much easier when typescript 3.7 lands. I can't wait to see `.tsd` being generated from jsdoc comments.

My feelings are the opposite :)
Using documentation to generate types seems so silly to me. If the library provides types, maintaining them is part of maintenance and there is no need to rewrite the lib in TS.
